// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./../../src/components/counter.vue')['default']
    H5Footer: typeof import('./../../src/components/h5-footer.vue')['default']
    H5Header: typeof import('./../../src/components/h5-header.vue')['default']
    'IBxl:bing': typeof import('~icons/bxl/bing')['default']
    'ICarbon:asleep': typeof import('~icons/carbon/asleep')['default']
    'ICarbon:awake': typeof import('~icons/carbon/awake')['default']
    'IIon:iosArrowBack': typeof import('~icons/ion/ios-arrow-back')['default']
    'IIon:languageOutline': typeof import('~icons/ion/language-outline')['default']
    ImageList: typeof import('./../../src/components/image-list.vue')['default']
    'IMdi:github': typeof import('~icons/mdi/github')['default']
    PcFooter: typeof import('./../../src/components/pc-footer.vue')['default']
    PcHeader: typeof import('./../../src/components/pc-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
